security:

    password_hashers:
            # Use native password hasher, which auto-selects and migrates the best
            # possible hashing algorithm (which currently is "bcrypt")
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
            
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # logout_on_user_change: true
            # anonymous: ~
            # pattern: ^/
            # form_login:
            #     login_path: login
            #     check_path: login_check
            #     always_use_default_target_path:  true
            #     default_target_path:  /
            # logout: ~           
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
